### ISSUE TITLE
SysTick interrupt doesn't work

### ISSUE THREAD

**Issue by kuldeepgade** [Chalandi/OSEK#5]
@Chalandi :Only Dispatcher(context switching) is working.

**Comment by kuldeepgade** [comment]
@Chalandi : Which ISR shall execute first?
Dispatcher or Cat2IsrWrapper?

**Comment by Chalandi** [comment]
@kuldeepgade you must enable the interrupt first. OSEK is supporting two kind of interrupts (Category 1 and Category 2).

Category 1 : low interrupt latency and transparent for the OS (are not allowed to use any OS service), to use this type of interrupts write your ISR handler address directly in the interrupt vector table.

Category 2: Could use the OS services (high latency compared to Cat1 due to the OS overhead) and can lead to a context switch by the end of the ISR execution (due the high prio scheduling algorithm), to use this type of interrupts you will need to set the OS ISR wrapper address (Cat2IsrWrapper) in the interrupt vector table and configure the "real" ISR in the OS Configuration (similar to the interrupt configured for the system timer).

The dispatcher is using PendSV Exception to switch the context and it should not be changed.

**Comment by kuldeepgade** [comment]
@Chalandi : Thanks

**Comment by kuldeepgade** [comment]
@Chalandi : I already have al these settings. But, in my case either of the interrupt executes-
Either Dispatcher or Cat2IsrWrapper. Both doesn't work together. Is there any limitation for using this code on Cortex-M0?

**Comment by kuldeepgade** [comment]
Thanks. It's working now.
